import { FamilyMember, MedicalRecord, Appointment, Doctor, Notification } from './types';

export const mockFamilyMembers: FamilyMember[] = [
  {
    id: 'FM001',
    familyId: 'FAM001',
    name: 'John Smith',
    dateOfBirth: '1985-05-15',
    bloodGroup: 'O+',
    relation: 'Self',
    gender: 'Male',
    allergies: ['Penicillin', 'Peanuts'],
    chronicConditions: ['Hypertension'],
  },
  {
    id: 'FM002',
    familyId: 'FAM001',
    name: 'Mary Smith',
    dateOfBirth: '1987-08-22',
    bloodGroup: 'A+',
    relation: 'Spouse',
    gender: 'Female',
    allergies: ['Latex'],
    chronicConditions: [],
  },
  {
    id: 'FM003',
    familyId: 'FAM001',
    name: 'Emma Smith',
    dateOfBirth: '2015-03-10',
    bloodGroup: 'O+',
    relation: 'Daughter',
    gender: 'Female',
    allergies: [],
    chronicConditions: ['Asthma'],
  },
];

export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: 'MR001',
    patientId: 'FM001',
    patientName: 'John Smith',
    date: '2026-03-15',
    diagnosis: 'Hypertension - Regular Checkup',
    prescription: 'Amlodipine 5mg - Once daily',
    doctorName: 'Dr. Sarah Johnson',
    notes: 'Blood pressure under control. Continue medication.',
  },
  {
    id: 'MR002',
    patientId: 'FM001',
    patientName: 'John Smith',
    date: '2026-01-20',
    diagnosis: 'Common Cold',
    prescription: 'Paracetamol 500mg - Twice daily for 3 days',
    doctorName: 'Dr. Michael Chen',
    notes: 'Rest and stay hydrated.',
  },
  {
    id: 'MR003',
    patientId: 'FM003',
    patientName: 'Emma Smith',
    date: '2026-02-28',
    diagnosis: 'Asthma - Follow-up',
    prescription: 'Albuterol Inhaler - As needed',
    doctorName: 'Dr. Emily Parker',
    notes: 'Asthma well controlled. No recent episodes.',
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 'APT001',
    patientId: 'FM001',
    patientName: 'John Smith',
    familyId: 'FAM001',
    doctorId: 'DOC001',
    doctorName: 'Dr. Sarah Johnson',
    specialty: 'Cardiology',
    date: '2026-04-15',
    time: '10:00 AM',
    status: 'scheduled',
    notes: 'Regular blood pressure checkup',
  },
  {
    id: 'APT002',
    patientId: 'FM002',
    patientName: 'Mary Smith',
    familyId: 'FAM001',
    doctorId: 'DOC003',
    doctorName: 'Dr. James Wilson',
    specialty: 'General Medicine',
    date: '2026-04-10',
    time: '2:00 PM',
    status: 'scheduled',
    notes: 'Annual health checkup',
  },
  {
    id: 'APT003',
    patientId: 'FM003',
    patientName: 'Emma Smith',
    familyId: 'FAM001',
    doctorId: 'DOC002',
    doctorName: 'Dr. Emily Parker',
    specialty: 'Pediatrics',
    date: '2026-04-08',
    time: '11:30 AM',
    status: 'scheduled',
    notes: 'Asthma follow-up',
  },
];

export const mockDoctors: Doctor[] = [
  {
    id: 'DOC001',
    name: 'Dr. Sarah Johnson',
    specialty: 'Cardiology',
    email: 'sarah.johnson@hospital.com',
    phone: '+1-555-0101',
    location: 'Central Hospital, Main Street',
    distance: '2.5 km',
    rating: 4.8,
    experience: 15,
    availability: ['Mon', 'Wed', 'Fri'],
  },
  {
    id: 'DOC002',
    name: 'Dr. Emily Parker',
    specialty: 'Pediatrics',
    email: 'emily.parker@hospital.com',
    phone: '+1-555-0102',
    location: 'Children\'s Clinic, Oak Avenue',
    distance: '1.8 km',
    rating: 4.9,
    experience: 12,
    availability: ['Mon', 'Tue', 'Thu'],
  },
  {
    id: 'DOC003',
    name: 'Dr. James Wilson',
    specialty: 'General Medicine',
    email: 'james.wilson@hospital.com',
    phone: '+1-555-0103',
    location: 'City Medical Center, Park Road',
    distance: '3.2 km',
    rating: 4.7,
    experience: 20,
    availability: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
  },
  {
    id: 'DOC004',
    name: 'Dr. Michael Chen',
    specialty: 'Orthopedics',
    email: 'michael.chen@hospital.com',
    phone: '+1-555-0104',
    location: 'Sports Medicine Clinic, Stadium Road',
    distance: '4.5 km',
    rating: 4.6,
    experience: 18,
    availability: ['Tue', 'Wed', 'Fri'],
  },
  {
    id: 'DOC005',
    name: 'Dr. Lisa Anderson',
    specialty: 'Dermatology',
    email: 'lisa.anderson@hospital.com',
    phone: '+1-555-0105',
    location: 'Skin Care Center, Beach Boulevard',
    distance: '5.0 km',
    rating: 4.8,
    experience: 10,
    availability: ['Mon', 'Wed', 'Thu', 'Fri'],
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'NOT001',
    type: 'reminder',
    title: 'Appointment Reminder',
    message: 'You have an appointment with Dr. Sarah Johnson tomorrow at 10:00 AM',
    timestamp: '2026-04-06T09:00:00',
    read: false,
  },
  {
    id: 'NOT002',
    type: 'appointment',
    title: 'Appointment Confirmed',
    message: 'Your appointment with Dr. Emily Parker has been confirmed for April 8th',
    timestamp: '2026-04-05T14:30:00',
    read: false,
  },
  {
    id: 'NOT003',
    type: 'system',
    title: 'Medical Records Updated',
    message: 'New medical record has been added to your profile',
    timestamp: '2026-04-04T11:15:00',
    read: true,
  },
];

// Mock data for doctors
export const mockDoctorAppointments: Appointment[] = [
  {
    id: 'APT001',
    patientId: 'FM001',
    patientName: 'John Smith',
    familyId: 'FAM001',
    doctorId: 'DOC001',
    doctorName: 'Dr. Sarah Johnson',
    specialty: 'Cardiology',
    date: '2026-04-07',
    time: '10:00 AM',
    status: 'scheduled',
    notes: 'Regular blood pressure checkup',
  },
  {
    id: 'APT004',
    patientId: 'FM005',
    patientName: 'Robert Brown',
    familyId: 'FAM002',
    doctorId: 'DOC001',
    doctorName: 'Dr. Sarah Johnson',
    specialty: 'Cardiology',
    date: '2026-04-07',
    time: '11:30 AM',
    status: 'scheduled',
    notes: 'Chest pain evaluation',
  },
  {
    id: 'APT005',
    patientId: 'FM006',
    patientName: 'Linda Davis',
    familyId: 'FAM003',
    doctorId: 'DOC001',
    doctorName: 'Dr. Sarah Johnson',
    specialty: 'Cardiology',
    date: '2026-04-07',
    time: '2:00 PM',
    status: 'scheduled',
    notes: 'Follow-up after angioplasty',
  },
  {
    id: 'APT006',
    patientId: 'FM007',
    patientName: 'Thomas Miller',
    familyId: 'FAM004',
    doctorId: 'DOC001',
    doctorName: 'Dr. Sarah Johnson',
    specialty: 'Cardiology',
    date: '2026-04-08',
    time: '9:00 AM',
    status: 'scheduled',
    notes: 'ECG test review',
  },
];
